targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - strict_raw_type
            - require_trailing_commas
            - cast_nullable_to_non_nullable
            - lines_longer_than_80_chars
