name: flutter_and_friends
description: The official Flutter & Friends conference app.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  conference_repository:
    path: packages/conference_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  path_provider: ^2.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
